server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      hostname: localhost

spring:
  clound:
    gateway:
      discovery:
        locator:
          enable: true
      routes:
        - id: negocio-service
          uri: lb://negocio-service
          predicates:
            - Path=/negocio/**
