server:
  port: 8092
  error: 
    include-message: always
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/bdo_negocio
    username: CITSE
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
